/**
 * Generated by orval v6.14.3 🍺
 * Do not edit manually.
 * Simulation API
 * OpenAPI spec version: 1.0.0
 */
export type GetSimulation200IndividualsItem = {
  x: number
  y: number
}

export type GetSimulation200 = {
  result: number
  individuals: GetSimulation200IndividualsItem[]
}

export type GetSimulationBody = {
  genetarion: number
  population: number
  problem: string
}

export type GetProblem200Item = {
  id: string
  name: string
}
